apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ddns.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "ddns.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "ddns.fullname" . }}
    spec:
      containers:
        - name: {{ include "ddns.fullname" . }}
          image: oznu/cloudflare-ddns:latest
          env:
            - name: ZONE
              value: {{ .Values.zone }}
            - name: SUBDOMAIN
              value: {{ .Values.subdomain }}
            - name: CRON
              value: "{{ .Values.cron }}"
            - name: DELETE_ON_STOP
              value: "{{ .Values.delete_on_stop }}"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "ddns.fullname" . }}
                  key: CLOUDFLARE_API_TOKEN
