service:
  annotations:
    metallb.universe.tf/address-pool: production
    metallb.universe.tf/allow-shared-ip: pihole-svc  
  externalTrafficPolicy: Local
  # Replace this with the metallb IP address you want pihole to respond to
  loadBalancerIP: 192.168.1.2
  serviceType: LoadBalancer
config:
  secrets:
  - name: WEBPASSWORD
    value: pihole
  env:
  - name: TZ
    value: "America/Edmonton"
  - name: PIHOLE_DNS_
    value: "1.1.1.1;8.8.8.8"
deployment:
  # Specify an image tag to force kube to pull it
  image: "pihole/pihole:latest"
  restartPolicy: Always
  # hostAliases:
  # - ip: 192.168.1.100
  #   hostnames:
  #     - foo
  #     - bar
storage:
  - name: pihole 
    size: 1Gi
    accessMode: ReadWriteOnce
    storageClass: freenas-nfs-csi
    mountPath: "/etc/pihole"
  - name: dnsmasq
    size: 100Mi
    accessMode: ReadWriteOnce
    storageClass: freenas-nfs-csi
    mountPath: "/etc/dnsmasq.d"