config:
  env:
  - name: TZ
    value: America/Edmonton
  - name: PIHOLE_DNS_
    value: 1.1.1.1;8.8.8.8
  secrets:
  - name: WEBPASSWORD
    value: b+JK**D&uEPW4mC])>Ro}2ms
deployment:
  image: pihole/pihole:latest
  restartPolicy: Always
service:
  annotations:
    metallb.universe.tf/address-pool: production
    metallb.universe.tf/allow-shared-ip: pihole-svc
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.100.50
  serviceType: LoadBalancer
storage:
- accessMode: ReadWriteOnce
  mountPath: /etc/pihole
  name: pihole
  size: 1Gi
  storageClass: freenas-nfs-csi
- accessMode: ReadWriteOnce
  mountPath: /etc/dnsmasq.d
  name: dnsmasq
  size: 100Mi
  storageClass: freenas-nfs-csi
