apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pihole.fullname" . }}
spec:
  selector:
    matchLabels:
        app: {{ include "pihole.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "pihole.fullname" . }}
    spec:
      {{- if .Values.deployment.hostAliases }}
      hostAliases:
        {{- toYaml .Values.deployment.hostAliases | nindent 8 }}
      {{- end }}
      containers:
      - name: pihole
        image: {{ .Values.deployment.image }}
        imagePullPolicy: IfNotPresent
        env:
        {{- range .Values.config.secrets }}
        - name: {{ .name }}
          valueFrom:
            secretKeyRef:
              name: {{ include "pihole.fullname" $ }}
              key: {{ .name }}
        {{- end }}
        {{- range .Values.config.env }}
        - name: {{ .name }}
          valueFrom:
            configMapKeyRef:
              name: {{ include "pihole.fullname" $ }}
              key: {{ .name }}
        {{- end }}
        volumeMounts:
          {{- range .Values.storage }}
            - name: {{ include "pihole.fullname" $ }}-{{ .name }}
              mountPath: {{ .mountPath }}
          {{- end }}
      restartPolicy: {{ .Values.deployment.restartPolicy }}
      volumes:
      {{- range .Values.storage }}
      - name: {{ include "pihole.fullname" $ }}-{{ .name }}
        persistentVolumeClaim:
            claimName: {{ include "pihole.fullname" $ }}-{{ .name }}
      {{- end }}
