{{- with .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.fullname" $ }}-tcp
  annotations:
    {{ toYaml .annotations | nindent 4 }}
spec:
    externalTrafficPolicy: {{ .externalTrafficPolicy }}
    loadBalancerIP: {{ .loadBalancerIP }}
    ports:
        # pihole use Ports to expose (53, 80, 67, 443), the bare minimum ports required for Pi-holes HTTP and DNS services
        - port: 80
          targetPort: 80
          name: port80
          protocol: TCP
        - port: 443
          targetPort: 443
          name: port443
          protocol: TCP
        - port: 53
          targetPort: 53
          protocol: TCP
          name: port53
    selector:
        app: {{ include "pihole.fullname" $ }}
    type: {{ .serviceType }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.fullname" $ }}-udp
  annotations:
    {{ toYaml .annotations | nindent 4 }}
spec:
    externalTrafficPolicy: {{ .externalTrafficPolicy }}
    loadBalancerIP: {{ .loadBalancerIP }}
    ports:
        - port: 53
          targetPort: 53
          protocol: UDP
          name: port53-udp
        - port: 67
          targetPort: 67
          protocol: UDP
          name: port67-udp
    selector:
        app: {{ include "pihole.fullname" $ }}
    type: {{ .serviceType }}
{{- end }}